# Building a Neural Network

## Back propagation from scratch in Python

### There's more...
In this section, we will build a simple neural network with a hidden layer that connects the input to the output on the same *toy dataset* that we worked on in the previous section. We define the model as follows:
* The input is connected to a hidden layer that has three units.
* The hidden layer is connected to the output, which has one unit in output layer.

1. Define the dataset and import the relevant packages:

In [130]:
import numpy as np
from copy import deepcopy

x = np.array([[1],[2],[3],[4]])
y = np.array([[2],[4],[6],[8]])

2. Initialize the weight and bias values randomly. The hidden layer has three units in it. Hence, there are a total of three weight values and three bias values.

   Additionally, the final layer has one unit that is connected to the three units of the hidden layer. Hence, a total of three weights and one bias dictate the value of the output layer.

   The randomly-initialized weights are as follows:
<div class="alert alert-block alert-success">
Generada en el proximo cuaderno!
</div>   

In [141]:
w = [np.array([[0.22940898, 0.77437544, 0.38963628]]),
     np.array([0., 0., 0.]),
     np.array([[-0.82037127],
               [-0.5443506 ],
               [ 1.193303  ]]),
     np.array([0.])]

3. Implement the feed-forward network where the hidden layer has a ReLU activation in it:

In [142]:
def feed_forward(inputs, outputs, weights):
    pre_hidden = np.dot(inputs,weights[0]) + weights[1]
    hidden = np.where(pre_hidden<0, 0, pre_hidden) 
    out = np.dot(hidden,weights[2]) + weights[3]
    squared_error = (np.square(out - outputs))
    return squared_error

4. Define the back-propagation function similarly to what we did in the previous section.

   We are updating each weight value by a small amount and then calculating the loss value corresponding to the updated weight value. Additionally, we are ensuring that the weight update happens across all weights and layers in the network.
   
   The change in the squared loss (`delta_loss`) is attributed to the change in the weight value.
   
   The weight value is updated (through weighing by the learning rate parameter).

In [143]:
def update_weights(inputs, outputs, weights, epochs):  
    for epoch in range(epochs):
        org_loss = feed_forward(inputs, outputs, weights)

        weights_new = deepcopy(weights)
        weights_new2 = deepcopy(weights)

        for i, layer in enumerate(reversed(weights)):
            # print(i, layer)
            for index, weight in np.ndenumerate(layer):
                # print(index, weight)
                weights_new[-(i+1)][index] += 0.0001
                # print('weights_new:', weights_new)
                loss = feed_forward(inputs, outputs, weights_new)
                # print('loss', loss)
                delta_loss = np.sum(org_loss - loss)/(0.0001*len(inputs))

                weights_new2[-(i+1)][index] += delta_loss*0.01
                weights_new = deepcopy(weights)

        weights = deepcopy(weights_new2)
        
    return weights_new2

And now, Run!

In [144]:
update_weights(x,y,w,1)

[array([[-0.03452322,  0.59924653,  0.77353113]]),
 array([-0.08797639, -0.05837586,  0.12796708]),
 array([[-0.74656696],
        [-0.29522557],
        [ 1.31865437]]),
 array([0.10723791])]

In [ ]:
from IPython.core.display import HTML
css_file = '.././styles/numericalmoocstyle.css'
HTML(open(css_file, 'r').read())